version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: user
  #     DB_PASSWORD: password
  #     DB_NAME: dbname
  #     REDIS_ADDR: redis:6379
  #     REDIS_PASSWORD: ""
  #     REDIS_DB: 0
  #   depends_on:
  #     - postgres
  #     - redis

volumes:
  postgres_data: